routes/web.php
<?php

Route::view('/', 'welcome');
Route::auth();

Route::get('/search', 'StudentController@search');
Route::get('/searching', 'StudentController@search');

Route::post('groups/{group}/students/{student}/uploadPhoto', 'StudentController@uploadPhoto');

Route::resource('groups.students', 'StudentController');
Route::resource('groups.students.marks', 'MarkController');

Route::resources([
    'subjects' => 'SubjectController',
    'groups' => 'GroupController',
]);

resources/views/student_statistics/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">      
        <form class="form-horizontal"
              action="{{url('groups/'.$currentStudent->group->id.'/students/'. $currentStudent->id ) }}" 
              enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            <div class="form-group">
                <div class="col-sm-6">
                    <label for="student-name" class="col-sm-3 control-label">
                        name
                    </label>
                    <input value="{{ $currentStudent->name }}" type="text" name="name" id="student-name" class="form-control">

                    <label for="student-birth" class="col-sm-3 control-label">
                        birth
                    </label>
                    <input value="{{ $currentStudent->birth }}" type="date" name="birth" id="student-birth" class="form-control">
                    <label for="student-group" class="col-sm-3 control-label">
                        group
                    </label>
                    <select id="student-group" name="group_id" class="form-control">
                        <option value="{{$currentStudent->group->id}}">{{ $currentStudent->group->name }}</option>
                        @foreach ($groups as  $group)
                        <option value="{{$group->id}}">{{$group->name}}</option>
                        @endforeach
                    </select><br>
                    <input type="submit" value="Обновить" class="btn btn-info">
                </div>
            </div>
        </form>
        <form class="form-horizontal" action="{{url('groups/'.$currentStudent->group->id.'/students/'. $currentStudent->id .'/uploadPhoto' ) }}" enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            <div class="form-group">
                <div class="col-sm-6">
                    <label for="student-phto" class="col-sm-3 control-label">
                        Upload a photo:
                    </label>
                    <input  value="photo" type="file" name="image" multiple accept="image/*">
                    <input type="submit" value="Загрузить фото" class="btn btn-info">
                </div>
            </div>
        </form>
<a style="margin-left: 15px;" class="btn btn-primary" href="{{ route('groups.students.show', [ $currentStudent->group, $currentStudent]) }}">Назад</a>
</div>
@endsection

resources/views/student_statistics/index.blade.php
@extends('layouts.app')

@section('content')

@can('store', \App\Models\Student::class)
<div class="panel-body">
    <!-- Display Validation Errors -->
    @include('common.errors')
    <!-- New group Form -->
    <form action="{{ route('groups.students.store', [ $group ]) }}" method="POST" class="form-horizontal">
        {{ csrf_field() }}

        <!-- group Name -->
        <div class="form-group">
            <label for="student-name" class="col-sm-3 control-label">
                student
            </label>

            <div class="col-sm-6">
                <input type="text" name="name" id="student-name" class="form-control">
            </div>
        </div>

        <!-- Add Task Button -->
        <div class="form-student">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> Add student
                </button>
            </div>
        </div>
    </form>
</div>
@endcan

<div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
        <table class="table table-striped task-table">

            <!-- Table Headings -->
            <thead>
            <th>name</th>
            <th>birth</th>
            </thead>
            @if (count($studentsInGroup) > 0)
            <!-- Table Body -->
            <tbody>
                @foreach ($studentsInGroup as $student)
                <tr>
                    <!-- student Name -->
                    <td class="table-text">
                        <div>{{ $student->name }}</div>
                    </td>
                    <!-- student birth -->
                    <td class="table-text">
                        <div>{{ $student->birth }}</div>
                    </td>
                    @can('destroy', $student)
                    <td>
                        <!--  Delete Button -->
                        <form action="{{ route('groups.students.destroy', [ $student->group, $student]) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}

                            <button type="submit" id="delete-group-{{ $student->id }}" class="btn btn-danger">
                                <i class="fa fa-btn fa-trash"></i>Delete
                            </button>
                        </form>
                    </td>
                    @endcan                
                    <!-- student bio -->
                    <td class="table-text">
                        <form id="update{{ $student->name }}"
                              action="{{ route('groups.students.show', [ $student->group, $student]) }}" method="GET">
                            {{ csrf_field() }}

                            <button type="submit" id="students-personal-{{ $student->id }}" class="btn btn-light">
                                <i class="fa fa-btn fa-trash"></i>see a bio
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach

            </tbody>
            @endif
        </table>
    </div>
</div>

@endsection

resources/views/student_statistics/search.blade.php
@extends('layouts.app')
@section('content')

<!-- Current students -->

<div class="panel panel-default">
    <div class="panel-heading">
        SEARCH PREFERENCIES 
    </div>
    <br>
    <div class="panel-body">

        <!-- Table Headings search -->

        <form action="{{ url('searching') }}" method="GET" class="form-horizontal" id="search">
            @csrf
            <div class="form-group">

                <label for="studentname">
                    student name
                </label>
                <input name="filter[name]" value="{{ request()->input("filter.name") }}" id="studentname">

                <label for="studentgroup">
                    student group
                </label>
                <select name="filter[group]" value="{{ request()->input("filter.group") }}" id="studentgroup">
                    <option></option>
                    @foreach ($groups as $group)
                    @if (request()->input("filter.group") == "$group->id")
                    <option selected value="{{ $group->id }}">{{ $group->name }}</option>
                    @else
                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                    @endif
                    @endforeach
                </select>

                <label for="studentaveragesince">
                    average since
                </label>
                <input type="number" placeholder="0" min="0" max="5" name="filter[av_since]" value="{{ request()->input("filter.av_since") }}"  id="studentaveragesince">

                <label for="studentaverageto">
                    to
                </label>
                <input type="number" placeholder="5" min="0" max="5" name="filter[av_to]" value="{{ request()->input("filter.av_to") }}" id="studentaverageto">
                <br>
                @foreach ($subjects as $subject)
                <label for="avg-since-{{ $subject->id }}">
                    average {{ $subject->name }} since
                </label>
                <input type="number" placeholder="since" min="0" max="5"
                       name="filterAvgSince[{{ $subject->id }}]" value="{{request()->input("filterAvgSince.$subject->id") }}" id="avg-since-{{$subject->id }}">
                <label for="avg-to-{{$subject->id }}">
                    to
                </label>
                <input type="number" placeholder="to" min="0" max="5"
                       name="filterAvgTo[{{ $subject->id }}]" value="{{ request()->input("filterAvgTo.$subject->id") }}" id="avg-to-{{$subject->id }}">
                <br>
                @endforeach

                <br>
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> Search
                </button>

                @if (request('sort'))
                @foreach (request('sort') as $sortField => $value)
                <input type="hidden" name="sort[{{$sortField}}]" value="{{ $value  }}" >
                @endforeach
                @endif



            </div>
        </form>

        <table class="table table-striped task-table">

            <!-- Table Headings -->
            <thead>
            <th>student<br>   
                <form action="{{ url('searching') }}" method="GET" class="form-horizontal" id="search2">
                    <select name="sort[student]"  value="{{ request()->input("sort.student") }}">
                        @if (request()->input("sort.student") == "asc")
                        <option></option>
                        <option selected=""  value="asc">asc</option>
                        <option value="desc">desc</option>
                        @elseif  (request()->input("sort.student") == "desc" )
                        <option></option>
                        <option  value="asc">asc</option>
                        <option selected="" value="desc">desc</option>
                        @else
                        <option></option>
                        <option  value="asc">asc</option>
                        <option  value="desc">desc</option>
                        @endif
                    </select>
                    <button type="submit">sort</button>
                    @if (request('filter'))
                    @foreach (request('filter') as $filterField => $value)
                    <input type="hidden" name="filter[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgSince'))
                    @foreach (request('filterAvgSince') as $filterField => $value)
                    <input type="hidden" name="filterAvgSince[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgTo'))
                    @foreach (request('filterAvgTo') as $filterField => $value)
                    <input type="hidden" name="filterAvgTo[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif
                </form>
            </th>
            <th>group<br>
                <form action="{{ url('searching') }}" method="GET" class="form-horizontal" id="search3">
                    <select  name="sort[group]" value="{{ request()->input("sort.group") }}">
                        @if (request()->input("sort.group") == "asc")
                        <option></option>
                        <option selected=""  value="asc">asc</option>
                        <option value="desc">desc</option>
                        @elseif  (request()->input("sort.group") == "desc")
                        <option></option>
                        <option  value="asc">asc</option>
                        <option selected="" value="desc">desc</option>
                        @else
                        <option></option>
                        <option  value="asc">asc</option>
                        <option  value="desc">desc</option>
                        @endif
                    </select>
                    <button type="submit">sort</button> 
                    @if (request('filter'))
                    @foreach (request('filter') as $filterField => $value)
                    <input type="hidden" name="filter[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgSince'))
                    @foreach (request('filterAvgSince') as $filterField => $value)
                    <input type="hidden" name="filterAvgSince[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgTo'))
                    @foreach (request('filterAvgTo') as $filterField => $value)
                    <input type="hidden" name="filterAvgTo[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif
                </form>
            </th>
            <th>average<br>
                <form action="{{ url('searching') }}" method="GET" class="form-horizontal" id="search4">
                    <select  name="sort[average]" value="{{ request()->input("sort.average") }}">
                        @if (request()->input("sort.average") == "asc")
                        <option></option>
                        <option selected=""  value="asc">asc</option>
                        <option value="desc">desc</option>
                        @elseif  (request()->input("sort.average") == "desc")
                        <option></option>
                        <option  value="asc">asc</option>
                        <option selected="" value="desc">desc</option>
                        @else
                        <option></option>
                        <option  value="asc">asc</option>
                        <option  value="desc">desc</option>
                        @endif
                    </select>
                    <button  type="submit">sort</button>  
                    @if (request('filter'))
                    @foreach (request('filter') as $filterField => $value)
                    <input type="hidden" name="filter[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgSince'))
                    @foreach (request('filterAvgSince') as $filterField => $value)
                    <input type="hidden" name="filterAvgSince[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgTo'))
                    @foreach (request('filterAvgTo') as $filterField => $value)
                    <input type="hidden" name="filterAvgTo[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif
                </form>
            </th>

            @foreach ($subjects as $subject)
            <th>average {{ $subject->name }}<br>
                <form action="{{ url('searching') }}" method="GET" class="form-horizontal">
                    <select  name="sort[avgSubject]" value="{{request()->input("sort.avgSubject")}}">
                        @if ( request()->input("sort.avgSubject") == "$subject->id"."_asc")
                        <option selected="" value="{{ $subject->id }}_asc">asc</option>
                        <option value="{{ $subject->id }}_desc">desc</option>
                        @elseif  ( request()->input("sort.avgSubject") ==  "$subject->id"."_desc")
                        <option  value="{{ $subject->id }}_asc">asc</option>
                        <option selected="" value="{{ $subject->id }}_desc">desc</option>
                        @else
                        <option></option>
                        <option  value="{{ $subject->id }}_asc">asc</option>
                        <option  value="{{ $subject->id }}_desc">desc</option>
                        @endif
                    </select>
                    <button  type="submit">sort</button>

                    @if (request('filter'))
                    @foreach (request('filter') as $filterField => $value)
                    <input type="hidden" name="filter[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgSince'))
                    @foreach (request('filterAvgSince') as $filterField => $value)
                    <input type="hidden" name="filterAvgSince[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif

                    @if (request('filterAvgTo'))
                    @foreach (request('filterAvgTo') as $filterField => $value)
                    <input type="hidden" name="filterAvgTo[{{$filterField}}]" value="{{ $value  }}" >
                    @endforeach
                    @endif
                </form>
            </th>
            @endforeach
            </thead>

            @if (count($students) > 0)
            <!-- Table Body -->
            <tbody>
                @foreach ($students as $student)
                <tr>
                    <!-- student Name -->
                    <td class="table-text">
                        <div>{{ $student->name }}</div>
                    </td>
                    <!-- group name -->

                    <td class="table-text">
                        <div>{{ $student->group["name"] }}</div>
                    </td>

                    <!-- student average -->
                    <td class="table-text">
                        <div>{{ $student->avg }}</div>
                    </td>

                    <!-- student average in subjects -->
                    @foreach ($subjects as $subject)

                    <td class="table-text">
                        <div>{{ $student->getAvgForSubject($subject) }}</div>
                    </td>

                    @endforeach
                </tr>

                @endforeach

            </tbody>
        </table>
    </div>
</div>
<div class="pagination">
    {{ $students->appends(request()->input())->links() }}
</div>
@endif

@endsection

resources/views/student_statistics/show.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
    <div class="panel-body">      
        <div class="panel-heading">
            Досье:
        </div>
        <img src="{{ $student->profilePhoto }}">
        <div>Имя: {{ $student->name }}</div>
        <div>Рождение: {{ $student->birth }}</div>
        <div>Группа: {{ $student->group->name }}</div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        Ratings
    </div>

    <form class="form-horizontal" action="{{url('groups/'.$student->group->id.'/students/'. $student->id .'/marks') }}" enctype="multipart/form-data" method="POST">
        {{ csrf_field() }}
        <div class="form-group">
            <div class="col-sm-6">
                <select name="subject_id" required="">
                    <option value="">subject</option>
                    @foreach ($subjects as  $subj)
                    <option  value="{{$subj->id}}">{{$subj->name}}</option>
                    @endforeach
                </select>
                <select name="mark" required="">
                    <option value="">mark</option>
                    <option  value="1">1</option>
                    <option  value="2">2</option>
                    <option  value="3">3</option>
                    <option  value="4">4</option>
                    <option  value="5">5</option>
                </select>
                <input type="submit" value="New mark">
            </div>
        </div>
    </form>

    <div class="panel-body user_subject_chart">
        @foreach ($student->grouppedMarks as $subject => $marks)
        <div class="user_mark_chart">
            <span>{{ $subject }}</span>
            @foreach ($marks as  $mark)
            <div class="user_inside_mark_chart">
                <span>{{ $mark->mark }}</span>
                <!--  Delete Button -->
                <form action="{{url('groups/'.$student->group->id.'/students/'. $student->id .'/marks/' .$mark->id) }}
                      " method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="user_inside_mark_button" type="submit" id="delete-studentsubjet-{{ $mark->id }}" >
                        Delete
                    </button>
                </form>

            </div>
            @endforeach
        </div>
        @endforeach            
    </div>
    
    <br>
    @can('edit', \App\Models\Student::class)
     <div class="panel-body user_subject_chart">      
        <div>      
            <form class="form-horizontal"
                  action="{{url('groups/'.$student->group->id.'/students/'. $student->id .'/edit' ) }}" method="GET">
                <div class="form-group">
                    <div class="col-sm-6">                 
                        <button type="submit" id="students-personal-{{ $student->id }}" class="btn btn-info">
                            <i class="fa fa-btn fa-trash"></i>Update bio
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @endcan

</div>



@endsection